# Generated by Django 5.1.4 on 2025-01-26 19:11

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageFirstBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'About Page First Banner',
                'verbose_name_plural': 'About Page First Banners',
            },
        ),
        migrations.CreateModel(
            name='AboutPageOurStorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
        migrations.CreateModel(
            name='AboutPageOurTeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name': 'Our Team Page',
                'verbose_name_plural': 'Our Team Pages',
            },
        ),
        migrations.CreateModel(
            name='AboutPageSecondBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'About Page Second Banner',
                'verbose_name_plural': 'About Page Second Banners',
            },
        ),
        migrations.CreateModel(
            name='AboutUsPageLastBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name': 'Our Team Last Banner',
                'verbose_name_plural': 'Our Team Last Banners',
            },
        ),
        migrations.CreateModel(
            name='BlogPageFistBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Blog Page First Banner',
                'verbose_name_plural': 'Blog Page First Banners',
            },
        ),
        migrations.CreateModel(
            name='BlogPageSecondBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Blog Page Second Banner',
                'verbose_name_plural': 'Blog Page Second Banners',
            },
        ),
        migrations.CreateModel(
            name='ContactPageFirstBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Contact Page First Banner',
                'verbose_name_plural': 'Contact Page First Banners',
            },
        ),
        migrations.CreateModel(
            name='ContactPageSecondBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Contact Page Second Banner',
                'verbose_name_plural': 'Contact Page Second Banners',
            },
        ),
        migrations.CreateModel(
            name='MainPageAboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name': 'About Us Section',
                'verbose_name_plural': 'About Us Sections',
            },
        ),
        migrations.CreateModel(
            name='MainPageFirstBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('back_image', models.ImageField(upload_to='common/images/')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Header Main Banner',
                'verbose_name_plural': 'Header Main Banners',
            },
        ),
        migrations.CreateModel(
            name='MainPageLastBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Main Page Last Banner',
                'verbose_name_plural': 'Main Page Last Banners',
            },
        ),
        migrations.CreateModel(
            name='MainPageOurMissionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name': 'Our Mission Section',
                'verbose_name_plural': 'Our Mission Sections',
            },
        ),
        migrations.CreateModel(
            name='MainPageOurPartnersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name': 'Our Partners Section',
                'verbose_name_plural': 'Our Partners Sections',
            },
        ),
        migrations.CreateModel(
            name='MainPageOurServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name': 'Services Section',
                'verbose_name_plural': 'Services Sections',
            },
        ),
        migrations.CreateModel(
            name='MainPageSecondBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Main Page Second Banner',
                'verbose_name_plural': 'Main Page Second Banners',
            },
        ),
        migrations.CreateModel(
            name='MainPageStatisticsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('first_number', models.IntegerField()),
                ('first_title', models.CharField(max_length=255)),
                ('second_number', models.IntegerField()),
                ('second_title', models.CharField(max_length=255)),
                ('third_number', models.IntegerField()),
                ('third_title', models.CharField(max_length=255)),
                ('fourth_number', models.IntegerField()),
                ('fourth_title', models.CharField(max_length=255)),
                ('right_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Statistics Section',
                'verbose_name_plural': 'Statistics Sections',
            },
        ),
        migrations.CreateModel(
            name='MainPageThirdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Main Page Third Banner',
                'verbose_name_plural': 'Main Page Third Banners',
            },
        ),
        migrations.CreateModel(
            name='OurProjectsPageFirstBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Our Projects Page First Banner',
                'verbose_name_plural': 'Our Projects Page First Banners',
            },
        ),
        migrations.CreateModel(
            name='OurServicesSecondBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Our Services Second Banner',
                'verbose_name_plural': 'Our Services Second Banners',
            },
        ),
        migrations.CreateModel(
            name='OurTeamPageFirstBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Our Team Page First Banner',
                'verbose_name_plural': 'Our Team Page First Banners',
            },
        ),
        migrations.CreateModel(
            name='OurTeamPageOurTeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name': 'Our Team Section',
                'verbose_name_plural': 'Our Team Sections',
            },
        ),
        migrations.CreateModel(
            name='OurTeamPageSecondBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Our Team Page Second Banner',
                'verbose_name_plural': 'Our Team Page Second Banners',
            },
        ),
        migrations.CreateModel(
            name='PostPageFirstBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Post Page First Banner',
                'verbose_name_plural': 'Post Page First Banners',
            },
        ),
        migrations.CreateModel(
            name='PostPageSecondBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Post Page Second Banner',
                'verbose_name_plural': 'Post Page Second Banners',
            },
        ),
        migrations.CreateModel(
            name='ServicesPageFirstBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('back_image', models.ImageField(upload_to='common/images/')),
            ],
            options={
                'verbose_name': 'Services Page First Banner',
                'verbose_name_plural': 'Services Page First Banners',
            },
        ),
    ]
