# Generated by Django 5.1.4 on 2025-02-08 18:16

import common.fields
import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagefirstbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='aboutpagesecondbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='aboutuspagelastbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='blogpagefistbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='blogpagesecondbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='contactpagefirstbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='contactpagesecondbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='mainpagefirstbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='mainpagelastbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='mainpagesecondbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='mainpagestatisticssection',
            name='right_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='mainpagethirdbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='ourprojectspagefirstbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='ourservicessecondbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='ourteampagefirstbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='ourteampagesecondbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='postpagefirstbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='postpagesecondbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
        migrations.AlterField(
            model_name='servicespagefirstbanner',
            name='back_image',
            field=common.fields.WEBPField(height_field='height', upload_to=common.models.image_folder, width_field='width'),
        ),
    ]
