# Generated by Django 5.1.4 on 2024-12-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('image', models.ImageField(upload_to='team_members/', verbose_name='Image')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('linked_in', models.CharField(blank=True, max_length=255, null=True, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.DeleteModel(
            name='PhotoReport',
        ),
    ]
