# Generated by Django 5.1.4 on 2024-12-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0004_smscampaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='hq',
            new_name='main',
        ),
    ]
